name: Build and Test

on: [push, pull_request]

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Build package
      run: scripts/build-wheel.sh
      shell: bash

    - name: Install package
      run: pip install -U assets/dist/tflite2onnx-*.whl

    - name: Install development dependencies
      run: pip install -r requirements.txt

    - name: Testing (collecting coverage data)
      run: coverage run --source=./tflite2onnx -m pytest

    # - name: SSH via Ngrok if fail
    #   if: ${{ failure() }}
    #   env:
    #     # Find token in: https://dashboard.ngrok.com/get-started/setup
    #     NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    #     NGROK_LOCAL_PASS: ${{ secrets.NGROK_LOCAL_PASS }}
    #   run: scripts/open-github-connection.sh
    # - name: Live instance if fail
    #   if: ${{ failure() }}
    #   run: sleep 1h

    - name: Upload coverage report
      continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        coverage xml
        bash <(curl -s https://codecov.io/bash)
